import React, { useState } from 'react';
import {
  FileText,
  Download,
  Copy,
  Check,
  X,
  Printer,
  ShieldCheck,
  CheckCircle2,
} from 'lucide-react';
import { formatDate } from '../utils/formatters';
import { useToast } from './Toast';

export function ReportExportModal({ isOpen, onClose, diagnosisData = {} }) {
  const { addToast } = useToast();
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const {
    case_id = 'CASE-001',
    diagnosis_id = 'DIAG-001',
    case_summary = {},
    rule_engine_findings = [],
    ai_diagnosis = {},
    review = {},
    status = 'DIAGNOSIS_SUPPORTED',
  } = diagnosisData;

  const generateMarkdownReport = () => {
    return `# CISCO TAC NETWORK DIAGNOSTIC & AUDIT REPORT
Generated by: NetSage AI (Cisco Networking Academy Lab Platform)
Date: ${new Date().toUTCString()}
Diagnostic Session ID: ${diagnosis_id}
Incident Identifier: ${case_id}

================================================================================
1. INCIDENT CLASSIFICATION & TAXONOMY
================================================================================
- Category: ${case_summary.category || 'General'}
- Severity: ${case_summary.severity || 'HIGH'}
- OSI Layer: ${case_summary.osi_layer || 'Layer 3 (Network)'}
- Observed Symptom: ${case_summary.symptom || 'N/A'}
- Evaluation Status: ${status}

================================================================================
2. DETERMINISTIC CISCO RULE ENGINE FINDINGS
================================================================================
${
  rule_engine_findings.length === 0
    ? 'No rule violations identified.'
    : rule_engine_findings
        .map(
          (r, i) =>
            `[Rule Check ${i + 1}] ${r.rule_id} - ${r.name} (${r.status || 'VIOLATION'})
Severity: ${r.severity}
Finding: ${r.message}
Evidence: ${r.evidence || 'N/A'}`
        )
        .join('\n\n')
}

================================================================================
3. AI ROOT CAUSE ANALYSIS & REMEDIATION PROPOSAL
================================================================================
- AI Confidence: ${Math.round((ai_diagnosis.confidence || 0.9) * 100)}%
- Root Cause: ${ai_diagnosis.root_cause || 'N/A'}
- Correlation: ${ai_diagnosis.evidence_correlation || 'N/A'}

[Proposed Cisco IOS Configuration Fix]
${ai_diagnosis.proposed_fix || 'No fix required.'}

[Verification Syntax]
${ai_diagnosis.verification_command || 'ping / show commands'}

================================================================================
4. HUMAN-IN-THE-LOOP AUDIT & SIGN-OFF
================================================================================
- Verdict: ${review?.status || 'PENDING_REVIEW'}
- Reviewer: ${review?.reviewer || 'Lead Network Engineer'}
- Timestamp: ${review?.timestamp ? formatDate(review.timestamp) : 'Pending Submission'}
- Reviewer Notes: ${review?.comment || 'Approved for change window.'}
${review?.corrected_diagnosis ? `- Corrected Diagnosis: ${review.corrected_diagnosis}` : ''}

================================================================================
DISCLAIMER: NetSage AI is an evidence-based advisory assistant. No network
configuration changes are executed automatically to production routers.
================================================================================
`;
  };

  const reportText = generateMarkdownReport();

  const handleCopy = () => {
    navigator.clipboard.writeText(reportText);
    setCopied(true);
    addToast('TAC Diagnostic Report copied to clipboard.', 'success');
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([reportText], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `cisco-tac-report-${case_id}-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
    addToast('Downloaded markdown TAC Audit Report.', 'info');
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/70 backdrop-blur-sm">
      <div className="w-full max-w-2xl bg-white dark:bg-[#0c1829] rounded-2xl border border-slate-200 dark:border-[#1e3450] shadow-2xl overflow-hidden flex flex-col max-h-[85vh]">
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-200 dark:border-[#1e3450] bg-slate-50/80 dark:bg-[#07101c] flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-xl bg-sky-50 dark:bg-sky-950/80 text-sky-600 dark:text-sky-400 border border-sky-200 dark:border-sky-800">
              <FileText className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-slate-900 dark:text-white">
                Cisco TAC Diagnostic & Audit Report
              </h3>
              <p className="text-[11px] text-slate-500 font-mono">
                Formal incident report for {case_id}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1 text-slate-400 hover:text-slate-600 dark:hover:text-white rounded-lg"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Report Preview */}
        <div className="flex-1 p-6 overflow-y-auto font-mono text-xs bg-slate-50 dark:bg-[#070f1a] text-slate-800 dark:text-slate-200 leading-relaxed whitespace-pre-wrap selection:bg-sky-500/20">
          {reportText}
        </div>

        {/* Footer Actions */}
        <div className="px-6 py-4 bg-white dark:bg-[#0c1829] border-t border-slate-200 dark:border-[#1e3450] flex items-center justify-between flex-wrap gap-3">
          <div className="flex items-center gap-1.5 text-xs text-slate-500 dark:text-slate-400 font-mono">
            <ShieldCheck className="w-4 h-4 text-emerald-500" />
            <span>Human-in-the-Loop Verified</span>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-slate-100 dark:bg-[#12243a] text-slate-700 dark:text-slate-200 hover:bg-slate-200 dark:hover:bg-[#18304e] text-xs font-mono font-bold border border-slate-200 dark:border-[#1e3450] transition-colors"
            >
              {copied ? (
                <>
                  <Check className="w-3.5 h-3.5 text-emerald-500" />
                  <span>Copied</span>
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5" />
                  <span>Copy Report</span>
                </>
              )}
            </button>

            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-sky-600 hover:bg-sky-500 text-white text-xs font-mono font-bold shadow-sm hover:shadow transition-all"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download .MD</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

export default ReportExportModal;
